apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: contosovacations-api-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: contosovacations-api-pod
    spec:
      containers:
      - name: contosovacations-api
        image: umaracr.azurecr.io/contosovacationsapi:v3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: contosovacations-api-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: contosovacations-api-pod
